# Generated by Django 3.2 on 2021-11-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='avatar/default.png', upload_to='avatar/%Y/%m', verbose_name='用户头像'),
        ),
    ]
