# Generated by Django 3.2 on 2021-12-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sign',
            field=models.CharField(blank=True, default='这个人很懒，什么都没有写', max_length=30, verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='昵称'),
        ),
    ]
