# Generated by Django 3.2 on 2021-11-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, editable=False, max_length=200, verbose_name='摘要'),
        ),
    ]
