# Generated by Django 3.2 on 2021-11-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comments',
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='cover/123.jpg', verbose_name='文章图片'),
        ),
    ]
