# Generated by Django 3.2 on 2021-12-17 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211216_2130'),
        ('blog', '0002_alter_article_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbs_up',
            field=models.PositiveIntegerField(
                default=0, verbose_name='点赞数'),
        ),
        migrations.CreateModel(
            name='ArticleStar',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('starTime', models.DateTimeField(
                    auto_now_add=True, verbose_name='收藏时间')),
                ('article', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='收藏文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='users.userprofile', verbose_name='收藏用户')),
            ],
            options={
                'verbose_name': '收藏数据',
                'verbose_name_plural': '收藏数据',
            },
        ),
        migrations.CreateModel(
            name='ArticlePraise',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('praiseTime', models.DateTimeField(
                    auto_now_add=True, verbose_name='点赞时间')),
                ('article', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='点赞文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='users.userprofile', verbose_name='点赞用户')),
            ],
            options={
                'verbose_name': '点赞数据',
                'verbose_name_plural': '点赞数据',
            },
        ),
    ]
