# Generated by Django 3.2 on 2021-11-28 04:05

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211127_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.user_directory_path, verbose_name='文章图片'),
        ),
    ]
