# Generated by Django 3.2 on 2021-12-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articlepraise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbs_up',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
