# Generated by Django 3.2 on 2021-11-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.PositiveBigIntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbs_up',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='点赞数'),
        ),
    ]
