# Generated by Django 3.2 on 2021-12-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211217_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='star',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='收藏数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbs_up',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='点赞数'),
        ),
    ]
