# Generated by Django 3.2 on 2021-12-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_thumbs_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(verbose_name='收藏用户')),
                ('articleId', models.IntegerField(verbose_name='收藏文章')),
                ('starTime', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
            ],
            options={
                'verbose_name': '收藏数据',
                'verbose_name_plural': '收藏数据',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='star',
            field=models.PositiveIntegerField(default=0, verbose_name='收藏数'),
        ),
    ]
