# Generated by Django 3.2 on 2021-11-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_sidebar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, '搜索'), (2, '最新文章'), (3, '热门文章'), (4, '文章归档'), (5, '标签云'), (6, '最近评论'), (7, 'HTML')], default=1, verbose_name='展示类型'),
        ),
    ]
