# Generated by Django 3.2 on 2021-12-17 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211216_2130'),
        ('blog', '0004_auto_20211217_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followTime', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
                ('followUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to='users.userprofile', verbose_name='关注用户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fo_user', to='users.userprofile', verbose_name='用户')),
            ],
            options={
                'verbose_name': '关注数据',
                'verbose_name_plural': '关注数据',
            },
        ),
        migrations.CreateModel(
            name='Fans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fansTime', models.DateTimeField(auto_now_add=True, verbose_name='粉丝关注时间')),
                ('fans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fans_user', to='users.userprofile', verbose_name='粉丝')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fa_user', to='users.userprofile', verbose_name='用户')),
            ],
            options={
                'verbose_name': '粉丝数据',
                'verbose_name_plural': '粉丝数据',
            },
        ),
    ]
