# Generated by Django 3.2 on 2021-12-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_fans_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='star',
            field=models.PositiveIntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbs_up',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
