# Generated by Django 3.2 on 2021-12-20 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20211217_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tui',
        ),
        migrations.DeleteModel(
            name='Recommend',
        ),
    ]
