# Generated by Django 3.2 on 2022-01-09 15:49

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_album_albumimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='album/album_default.jpg', upload_to=blog.models.album_path, verbose_name='相册封面'),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='image',
            field=models.ImageField(upload_to=blog.models.album_pic_path, verbose_name='相册图片'),
        ),
    ]
