# Generated by Django 3.2 on 2022-01-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20220109_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumimage',
            old_name='category',
            new_name='album',
        ),
    ]
