# Generated by Django 3.2 on 2022-01-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_category_albumimage_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, default='这是一个普通的相册', max_length=500, verbose_name='描述'),
        ),
    ]
